name: Cypress Tests

on:
  pull_request:
    types: [opened, reopened]

# on:
#   pull_request:
#     branches:
#       - main
#     types: [opened]

jobs:
  cypress-run:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change String Case
        id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.event.deployment_status.environment }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_VERCEL_ENV: ${{ steps.string.outputs.lowercase }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_MA_EMAIL_DOMAIN_STAGING: ${{ secrets.MA_EMAIL_DOMAIN_STAGING }}
          CYPRESS_MA_EMAIL_DOMAIN_PROD: ${{ secrets.MA_EMAIL_DOMAIN_PROD }}
          CYPRESS_IM_EMAIL_DOMAIN_STAGING: ${{ secrets.IM_EMAIL_DOMAIN_STAGING }}
          CYPRESS_IM_EMAIL_DOMAIN_PROD: ${{ secrets.IM_EMAIL_DOMAIN_PROD }}
          CYPRESS_ECOM_OTP_EMAIL_DOMAIN_STAGING: ${{ secrets.ECOM_OTP_EMAIL_DOMAIN_STAGING }}
          CYPRESS_ECOM_OTP_EMAIL_DOMAIN_PROD: ${{ secrets.ECOM_OTP_EMAIL_DOMAIN_PROD }}
        with:
          browser: chrome
          record: true

      - name: Assign PR when fails
        if: ${{ failure() }}
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: manalliaquat
